steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops:latest', '.']

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops:latest']

  # Apply the Kubernetes configuration
  
  - args: 
        - run
        - --name== 'gcr.io/cloud-builders/gke-deploy'
        
        - --filename=gke.yaml
        - --image=gcr.io/$PROJECT_ID/gcpdevops
        - --location=us-central1-c
        - --cluster=gcp-devops-project
        - --namespace=gcp-devops-prod
