apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
        - name: gcp-devops-gke
          image: gcr.io/gke-dev-project-397211/gcpdevops:latest
          ports:
            - containerPort: 5000 # Replace with the port your application listens on
