apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mygcp
  template:
    metadata:
      labels:
        app: mygcp
    spec:
      containers:
      - name: gcp-devops-gke  # Corrected indentation here
        image: gcr.io/gke-dev-project-397211/gcpdevops
        ports:
        - containerPort: 5000
       # env:
        #- name: PORT
         # value: "5000"
