apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
        - name: gcp-devops-gke
          image: gcr.io/gke-dev-project-397211/gcpdevops:latest
          #ports:
            #- containerPort: 5000 # Replace with the port your application listens on
