apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: gcr.io/gke-dev-project-397211/gcpdevops:latest
          #ports:
           # - containerPort: 8080 # Replace with the port your application listens on
          #env:
           # - name: PORT
            #  value: "5000"
